GET localhost:8080/v1/test/
Content-Type: application/json

###

POST localhost:8080/v1/users/
Content-Type: application/json

{
  "username": "test1",
  "email": "test1"
}

###

GET localhost:8080/v1/users/
Content-Type: application/json

###

POST localhost:8080/v1/users/login
Content-Type: application/json

{
  "email": "test1",
  "password": "test"
}

###

GET localhost:8080/v1/boards?userId=3
Content-Type: application/json

###

POST localhost:8080/v1/boards/
Content-Type: application/json

{
  "name": "Board2",
  "userId": 3
}

###

POST localhost:8080/v1/boards/3/fav
Content-Type: application/json

###

DELETE localhost:8080/v1/boards/3
Content-Type: application/json

###
