GET localhost:8080/v1/test/
Content-Type: application/json

###

POST localhost:8080/randomeal/v1/users/
Content-Type: application/json

{
  "username": "test1",
  "email": "test1"
}

###

GET localhost:8080/randomeal/v1/users/
Content-Type: application/json

###

POST localhost:8080/randomeal/v1/users/login
Content-Type: application/json

{
  "email": "test1",
  "password": "test1"
}

###

GET localhost:8080/randomeal/v1/boards?userId=1
Content-Type: application/json

###

POST localhost:8080/randomeal/v1/boards/
Content-Type: application/json

{
  "name": "Board2",
  "userId": 1
}

###

PUT localhost:8080/randomeal/v1/boards/1/fav
Content-Type: application/json

###

DELETE localhost:8080/randomeal/v1/boards/3
Content-Type: application/json

###

GET localhost:8080/randomeal/v1/dishes/1
Content-Type: application/json

###

GET localhost:8080/randomeal/v1/dishes/
Content-Type: application/json

###

DELETE localhost:8080/randomeal/v1/boards/1/dishes/1
Content-Type: application/json

###

POST localhost:8080/randomeal/v1/boards/1/dishes/1
Content-Type: application/json

###

GET http://192.168.100.3:8080/randomeal/v1/boards/1
Content-Type: application/json

###