spring:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/randomeal
    username: postgres
    password: password
  flyway:
    baseline-on-migrate: true
logging:
  level:
    pi.hci: debug
